# Generated by Django 5.0.2 on 2024-02-21 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='balance',
        ),
    ]
