# Generated by Django 5.0.2 on 2024-02-21 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_transaction_delete_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
    ]
